services:
  - type: web
    name: arutourism
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    preDeployCommand: |
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn arutourism.wsgi:application --bind 0.0.0.0:$PORT