# Generated by Django 4.2.21 on 2025-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
