# Generated by Django 4.2.23 on 2025-08-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='app_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cadastrur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contato_direto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='digital',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco_full',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='maps_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagem',
            field=models.ImageField(default='placeholders/sem_imagem.png', upload_to='empresas/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='latitude',
            field=models.CharField(default='-28.937100', max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='longitude',
            field=models.CharField(default='-49.484000', max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rua',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['categoria'], name='core_empres_categor_a5ab9f_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cidade', 'bairro'], name='core_empres_cidade_5328ce_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cnpj'], name='core_empres_cnpj_70d9ec_idx'),
        ),
    ]
