# Generated by Django 4.2.21 on 2025-06-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='sem_email_telefone',
        ),
    ]
