# Generated by Django 4.2.21 on 2025-06-12 00:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresa_latitude_alter_empresa_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
