# Generated by Django 4.2.21 on 2025-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_empresa_facebook_remove_empresa_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sem_email_telefone',
            field=models.BooleanField(default=False),
        ),
    ]
