# Generated by Django 4.2.23 on 2025-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilusuario_avatar_perfilusuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/'),
        ),
    ]
