# Generated by Django 4.2.24 on 2025-09-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_empresa_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveIndex(
            model_name='empresa',
            name='core_empres_categor_a5ab9f_idx',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='empresa',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='core.tag'),
        ),
    ]
