# Generated by Django 4.2.24 on 2025-09-12 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_migrate_categorias_to_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.tag'),
        ),
    ]
