# Generated by Django 4.2.24 on 2025-10-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_default_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, help_text='Usado na URL da empresa. Deixe em branco para gerar automaticamente.', max_length=255, null=True, unique=True),
        ),
    ]
