# Generated by Django 4.2.24 on 2025-10-03 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_populate_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='imagem',
        ),
        migrations.CreateModel(
            name='ImagemEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='empresas/galeria/')),
                ('principal', models.BooleanField(default=False, help_text='Marque se esta é a imagem principal/capa da empresa.')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.empresa')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('principal'), descending=True), '-data_upload'],
            },
        ),
    ]
