# Generated by Django 4.2.24 on 2025-10-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
