# Generated by Django 4.2.24 on 2025-10-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_empresa_facebook_alter_empresa_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='core.empresa'),
        ),
    ]
