# Generated by Django 4.2.24 on 2025-10-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_perfilusuario_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='horario_domingo',
            field=models.CharField(blank=True, help_text='Ex: Fechado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='horario_observacoes',
            field=models.TextField(blank=True, help_text="Informações adicionais, como 'Fechado para almoço das 12h às 13h'.", null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='horario_sabado',
            field=models.CharField(blank=True, help_text='Ex: 09:00 - 12:00 ou Fechado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='horario_semana',
            field=models.CharField(blank=True, help_text='Ex: 09:00 - 18:00', max_length=100, null=True),
        ),
    ]
