# Generated by Django 4.2.24 on 2025-10-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_empresa_horario_domingo_empresa_horario_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tema_preferido',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('contrast', 'Alto Contraste')], default='light', max_length=10, verbose_name='Tema de preferência'),
        ),
    ]
