# Generated by Django 4.2.24 on 2025-10-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_perfilusuario_tema_preferido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True, unique=True),
        ),
    ]
