# Generated by Django 4.2.13 on 2025-10-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='empresa',
            name='core_empres_cnpj_70d9ec_idx',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='app_url',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='horario_domingo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='horario_observacoes',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='horario_sabado',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='horario_semana',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='maps_url',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='site',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cpf_cnpj',
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='core.empresa', verbose_name='Empresas Favoritas'),
        ),
    ]
