# Generated by Django 5.2.1 on 2025-05-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('restaurante', 'Restaurante'), ('hotel', 'Hotel'), ('ponto_turistico', 'Ponto Turístico')], max_length=50)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='empresa_imagens/')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
