# Generated by Django 4.2.21 on 2025-05-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
