# Generated by Django 4.2.21 on 2025-05-25 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empresa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
