# Generated by Django 4.2.21 on 2025-05-29 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_empresa_data_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='endereco',
            new_name='rua',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(default='sem bairro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(default='00000-000', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(default='testecidade', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(default=67, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.categoria'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
